# CIFAR10 / VGG16 / 4-bit
dataset:
  name: cifar10
  data_root: ./data
  batch_size: 128
  num_workers: 2

model:
  name: vgg16

training:
  fp32_epochs: 200
  fp32_lr: 0.05
  epochs: 30
  lr: 0.0001

quantization:
  bits: 4
