# CIFAR100 / VIT-TINY / 2-bit
dataset:
  name: cifar100
  data_root: ./data
  batch_size: 128
  num_workers: 2

model:
  name: vit_tiny

training:
  fp32_epochs: 200
  fp32_lr: 0.001
  epochs: 30
  lr: 5e-05

quantization:
  bits: 2
