# TINY-IMAGENET / RESNET34 / 8-bit
dataset:
  name: tiny_imagenet
  data_root: ./data
  batch_size: 128
  num_workers: 4

model:
  name: resnet34

training:
  fp32_epochs: 100
  fp32_lr: 0.1
  epochs: 30
  lr: 0.0001

quantization:
  bits: 8
